// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/task/data/models/task_model.dart';
import 'features/todo_list/data/models/todo_list_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1690885529057212971),
    name: 'TaskModel',
    lastPropertyId: const obx_int.IdUid(9, 8015525665761591200),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5624061407787491873),
        name: 'dbId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4310829647114329982),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 3083953889607998642),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 119723695490749685),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1954846521336250590),
        name: 'isCompleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3671169589932087563),
        name: 'isMyDay',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6014515769461889458),
        name: 'isStarred',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8451659814937932839),
        name: 'listUuid',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 104732166719960421),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 934902091420073567),
        name: 'dueDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8015525665761591200),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 3429127083449637149),
    name: 'TodoListModel',
    lastPropertyId: const obx_int.IdUid(4, 7968866419107947935),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2438763169715901209),
        name: 'dbId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4404497033337141966),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 3898642417476134460),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 463775457450164091),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7968866419107947935),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 3429127083449637149),
    lastIndexId: const obx_int.IdUid(3, 3898642417476134460),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    TaskModel: obx_int.EntityDefinition<TaskModel>(
      model: _entities[0],
      toOneRelations: (TaskModel object) => [],
      toManyRelations: (TaskModel object) => {},
      getId: (TaskModel object) => object.dbId,
      setId: (TaskModel object, int id) {
        object.dbId = id;
      },
      objectToFB: (TaskModel object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final titleOffset = fbb.writeString(object.title);
        final listUuidOffset = fbb.writeString(object.listUuid);
        fbb.startTable(10);
        fbb.addInt64(0, object.dbId);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addBool(3, object.isCompleted);
        fbb.addBool(4, object.isMyDay);
        fbb.addBool(5, object.isStarred);
        fbb.addOffset(6, listUuidOffset);
        fbb.addInt64(7, object.dueDate?.millisecondsSinceEpoch);
        fbb.addInt64(8, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.dbId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dueDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final dbIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final listUuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final isCompletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final isMyDayParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final isStarredParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final dueDateParam = dueDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(dueDateValue);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final object = TaskModel(
          dbId: dbIdParam,
          uuid: uuidParam,
          title: titleParam,
          listUuid: listUuidParam,
          isCompleted: isCompletedParam,
          isMyDay: isMyDayParam,
          isStarred: isStarredParam,
          dueDate: dueDateParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
    TodoListModel: obx_int.EntityDefinition<TodoListModel>(
      model: _entities[1],
      toOneRelations: (TodoListModel object) => [],
      toManyRelations: (TodoListModel object) => {},
      getId: (TodoListModel object) => object.dbId,
      setId: (TodoListModel object, int id) {
        object.dbId = id;
      },
      objectToFB: (TodoListModel object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(5);
        fbb.addInt64(0, object.dbId);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.dbId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dbIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final object = TodoListModel(
          dbId: dbIdParam,
          uuid: uuidParam,
          name: nameParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [TaskModel] entity fields to define ObjectBox queries.
class TaskModel_ {
  /// See [TaskModel.dbId].
  static final dbId = obx.QueryIntegerProperty<TaskModel>(
    _entities[0].properties[0],
  );

  /// See [TaskModel.uuid].
  static final uuid = obx.QueryStringProperty<TaskModel>(
    _entities[0].properties[1],
  );

  /// See [TaskModel.title].
  static final title = obx.QueryStringProperty<TaskModel>(
    _entities[0].properties[2],
  );

  /// See [TaskModel.isCompleted].
  static final isCompleted = obx.QueryBooleanProperty<TaskModel>(
    _entities[0].properties[3],
  );

  /// See [TaskModel.isMyDay].
  static final isMyDay = obx.QueryBooleanProperty<TaskModel>(
    _entities[0].properties[4],
  );

  /// See [TaskModel.isStarred].
  static final isStarred = obx.QueryBooleanProperty<TaskModel>(
    _entities[0].properties[5],
  );

  /// See [TaskModel.listUuid].
  static final listUuid = obx.QueryStringProperty<TaskModel>(
    _entities[0].properties[6],
  );

  /// See [TaskModel.dueDate].
  static final dueDate = obx.QueryDateProperty<TaskModel>(
    _entities[0].properties[7],
  );

  /// See [TaskModel.createdAt].
  static final createdAt = obx.QueryDateProperty<TaskModel>(
    _entities[0].properties[8],
  );
}

/// [TodoListModel] entity fields to define ObjectBox queries.
class TodoListModel_ {
  /// See [TodoListModel.dbId].
  static final dbId = obx.QueryIntegerProperty<TodoListModel>(
    _entities[1].properties[0],
  );

  /// See [TodoListModel.uuid].
  static final uuid = obx.QueryStringProperty<TodoListModel>(
    _entities[1].properties[1],
  );

  /// See [TodoListModel.name].
  static final name = obx.QueryStringProperty<TodoListModel>(
    _entities[1].properties[2],
  );

  /// See [TodoListModel.createdAt].
  static final createdAt = obx.QueryDateProperty<TodoListModel>(
    _entities[1].properties[3],
  );
}
